version: '2'

services:
  localstack:
    image: localstack/localstack-full:latest
    container_name: localstack_demo
    networks:
      skynet:
        ipv4_address: 172.21.0.8
    ports:
      - "4566:4566" # Edge Port
      - "4569:4569" # Dynamo DB Port
      - "4571:4571" # Elasticsearch Port
      - "4572:4572" # S3 Port
      - "4574:4574" # Lambda Port
      - "8080:8080" # Web-UI Port
#    networks:
#      skynet:
#        ipv4_address: 172.20.0.7
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  s3-app:
    depends_on:
      - localstack
    build:
      context: ./s3
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      skynet:
        ipv4_address: 172.21.0.4
networks:
  skynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
