version: '3'

volumes:
  s3-data:
    external: true

services:
  localstack:
    image: localstack/localstack-full:latest
    container_name: localstack
    ports:
      - "4566:4566" # Edge Port
      - "4569:4569" # Dynamo DB Port
      - "4571:4571" # Elasticsearch Port
      - "4572:4572" # S3 Port
      - "4574:4574" # Lambda Port
      - "8080:8080" # Web-UI Port
    networks:
      - skynet-s3
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/s3/data
      - PORT_WEB_UI=8080
    volumes:
      - s3-data:/var/lib/s3
  s3-app:
      depends_on:
        - localstack
      build:
        context: ./s3
        dockerfile: Dockerfile
      networks:
        - skynet-s3
      ports:
        - 8082:8082
networks:
  skynet-s3:
    name: "skynet-s3"